### ISSUE TITLE
Blueprint Documentation

### ISSUE THREAD

**Issue by freezernick** [Free2Play-Entertainment/ue-gjapi-core#15]

**Comment by mrtajniak** [comment]
Hi, I have a question, when will the documentation be available?

**Comment by freezernick** [comment]
That's a good question. I've just started to work on the [(BP)-API Reference](https://github.com/Free2Play-Entertainment/ue-gjapi-core/wiki/Blueprint-API) and I would love it being done on the weekend, but I can't make any promises. I will make an announcement on the GameJolt Page when it's ready

**Comment by freezernick** [comment]
Moved to https://github.com/Free2Play-Entertainment/ue-gjapi-core/wiki

Will be done this weekend
